import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/__molecules/Header/Header";
import Footer from "./components/__molecules/footer/Footer";
import { ThemeProvider } from "./components/__molecules/themecontext/ThemeContext";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Facebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white p-1`}
      >
        <Header />
        <ThemeProvider>
          <div className="mt-[50px]">{children}</div>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
